Attempt to make the Definition docs a bit better
hmrc/accessibility pull request #45
Opened 2020-10-06 15:46 UTC by philsherry

Gave these docs an overhaul:

- Definition of Ready
- Definition of Done

The first one was just a legacy list of _things_ that never really made sense.

2020-10-07 09:02 UTC, adamliptrot-oc requested changes

2020-10-07 09:02 UTC, adamliptrot-oc commented on docs/definition-of-ready.md
> +- provide a warning when an action takes the user to a different tab or window
"_provide a warning when an action **will take** the user ..._"

2020-10-07 09:02 UTC, adamliptrot-oc commented on docs/definition-of-ready.md
> +- all form elements have accessible names
all **interactive** elements instead of just **form**?

2021-05-21 10:37 UTC, philsherry commented on docs/definition-of-ready.md
> +- [established patterns](#established-patterns)
These sections should certainly have more things in them, but this was all I thought of at the time. I think it's valid, but feel free to add further items.

2021-05-21 10:38 UTC, philsherry commented on docs/definition-of-ready.md
> +- there should reasonable distance between related elements, rather than remote from each other
We discussed this on Slack at the time—this was _your own wording_. 😆

2021-05-21 11:58 UTC, philsherry commented
This has got a bit out of control due to that unverified commit at the top of the chain, so I'll close this before it gets any worse and breaks GitHub.

2021-05-21 11:58 UTC, closed without merging